CREATE TABLE CityProject (
    id NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL,
    Latitude NUMBER CONSTRAINT Latitude
        CHECK ((Latitude >= -90) AND (Latitude <= 90)) ,
    Longitude NUMBER CONSTRAINT Longitude
        CHECK ((Longitude >= -180) AND (Longitude <= 180))
);

CREATE TABLE Group1 (
    id NUMBER(10),
    name varchar(255),
    Latitude NUMBER,
    Longitude NUMBER
);

CREATE TABLE Group2 (
    id NUMBER(10),
    name varchar(255),
    Latitude NUMBER,
    Longitude NUMBER
);